BUG: Fixed error when findBrowserForSequence(inputVolSeq) fails
Error report:

[INFO][Stream] 09.10.2017 15:07:40 [] (unknown:0) - Registration is completed
[INFO][Stream] 09.10.2017 15:07:40 [] (unknown:0) - 'NoneType' object has no attribute 'SetOverwriteProxyName'
[CRITICAL][Stream] 09.10.2017 15:07:40 [] (unknown:0) - Traceback (most recent call last):
[CRITICAL][Stream] 09.10.2017 15:07:40 [] (unknown:0) -   File "C:/Users/salewis/AppData/Roaming/NA-MIC/Extensions-26351/SequenceRegistration/lib/Slicer-4.7/qt-scripted-modules/SequenceRegistration.py", line 271, in onApplyButton
[CRITICAL][Stream] 09.10.2017 15:07:40 [] (unknown:0) -     int(self.initialFixedFrame.value), self.registrationPresetSelector.currentIndex)
[CRITICAL][Stream] 09.10.2017 15:07:40 [] (unknown:0) -   File "C:/Users/salewis/AppData/Roaming/NA-MIC/Extensions-26351/SequenceRegistration/lib/Slicer-4.7/qt-scripted-modules/SequenceRegistration.py", line 431, in registerVolumeSequence
[CRITICAL][Stream] 09.10.2017 15:07:40 [] (unknown:0) -     outputBrowserNode.SetOverwriteProxyName(inputVolSeq, True)
[CRITICAL][Stream] 09.10.2017 15:07:40 [] (unknown:0) - AttributeError: 'NoneType' object has no attribute 'SetOverwriteProxyName'
[WARNING][VTK] 09.10.2017 15:07:40 [] (unknown:0) - Generic Warning: In C:\D\N\Slicer-0-build\VTKv8\Common\Core\vtkDebugLeaks.cxx, line 281

Solution:

Instead of just adding a check, removed changing of SetOverwriteProxyName for the input sequence, as modifying inputs would be an unexpected side effect (and users can change the setting in Sequence browser module anyway).